### PR TITLE
group resources together and fix typos in readmes

### PR DESCRIPTION
**Pull request by rberrelleza**

### CODE REVIEW

**Review by pchico83 — APPROVED** [review]
Nice idea!
Could you do the same for the django, php and node samples?

**Comment by rberrelleza** [comment]
> Nice idea!
> Could you do the same for the django, php and node samples?

yep, I'll do it this PR as well

**Comment by rberrelleza** [comment]
Deleteing the node sample will break https://okteto.com/docs/samples/node/index.html, what do we do about it? Port it to use the new application feature?

**Review by pchico83 — APPROVED** [review]

**Comment by pchico83** [comment]
@rberrelleza we should use https://github.com/okteto/node-getting-started/blob/master/README.md

**Pull request merged**
