### PR TITLE
Move default port from 8000 to 8080

### PR DESCRIPTION
**Pull request by pchico83**

### CODE REVIEW

**Review by rberrelleza — APPROVED** [review]
We also need to rebuild the docker image for vote (the one we use in the getting started)

**Comment by pchico83** [comment]
@rberrelleza for the getting started we only use the official python image (the dev env).

**Review by rlamana — APPROVED** [review]

**Comment by rberrelleza** [comment]
@pchico83 we also mention the container in the part where you talk about `okteto run`

**Comment by pchico83** [comment]
@rberrelleza right. we need to rebuild images for the three examples then

**Pull request merged**
